language: bash
branches:
    - travis
    - install_refactor
before_install:
    - git clone https://github.com/sstephenson/bats.git && cd bats && sudo ./install.sh /usr/local && cd -
install: true
script: bats tests
