language: bash
branches:
    - travis
    - master
before_install:
    - git clone https://github.com/sstephenson/bats.git
    - cd bats
    - sudo ./install.sh /usr/local
    - cd -
    # Add ourselves to a test group for permissions tests.
    - sudo addgroup doily_test
    - sudo usermod -aG doily_test $USER
install: true
# Run inside a subshell so the group membership kicks in.
script: sudo -E su $USER -c "bats tests"
