language: bash
branches:
    - travis
    - master
before_install:
    - git clone https://github.com/sstephenson/bats.git
    - cd bats
    - sudo ./install.sh /usr/local
    - cd -
    # This fixes a known bug in Bats (https://github.com/sstephenson/bats/issues/140#issuecomment-206756745)
    - bash tests/fix_bats.sh
install: true
script: bats tests
